### ISSUE TITLE
Using tags instead of fields

### ISSUE THREAD

**Issue by yugene** [influxdata/nginx-influxdb-module#14]
Hello!

Is there any reason to send all the metrics as InfluxDB fields? I guess that the following fields should be sent as tags: method, status, uri, extension, content_type.

**Comment by pmoncadaisla** [comment]
👍 +1
I've filled in this PR: https://github.com/influxdata/nginx-influxdb-module/pull/15/ for this exact request!

**Comment by fntlnz** [comment]
@yugene @pmoncadaisla you probably want this because tags are easier and more efficient to query than fields, I agree with that. 

Initially we used fields because we didn't want to increase the cardinality of the final dataset, this is especially true for the `uri`.

So what we want to do here I think is to have `method`, `status`, `extension` and `content_type` as fields and tags while leaving `uri` only as field.

**Comment by fntlnz** [comment]
I've been thinking a bit more about this, and now I remembered the initial reason for which everything was a field here.
The main reason was that using fields was less expensive on a database point of view (e.g: lower cardinality) while for example different users/configurations will want different combinations of the fields/tags in this case.

So, since this module can only be used with `udp` and increasing the length of the line is not a good idea (MTU and udp packets constraints) the idea we had was that if one needs something different than the default configuration she/he can achieve that using telegraf with the [socket listerner input](https://github.com/influxdata/telegraf/tree/release-1.6/plugins/inputs/socket_listener) and [InfluxDB output](https://github.com/influxdata/telegraf/tree/release-1.7/plugins/outputs).

For example, to convert fields to tags and vice-versa you can use the [Converter processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/converter#converter-processor) that's designed to do that and only that.

**Comment by pmoncadaisla** [comment]
You are right about the cardinality @fntlnz. In my case the measurament without tags is useless, but as you said it can also be achieved using Telegraf as proxy, or oven using Kapacitor (as you suggested me), which I think it is even a better approach!

I can live with the no tags implementations (as it is right now) and try a different approach to get useful data.

Thanks a lot!

**Comment by yugene** [comment]
@fntlnz, @pmoncadaisla, thank you! We'll try the Converter.

**Comment by JorgeStefanov** [comment]
Its been a while since this issue was opened and last commented but the resolution appeared to be simpler than anyone thought.
In the first line after server_name="$you_server_name" just add a comma as separator and specify the tags you want. Simple as that.

I've set up Telegraf to receive the data from nginx-influxdb-module and then convert the desired fields to tags and it was working but this is just gold :D.. Enjoy

In my case, just for a test, I added:

tag=js 
tag_value=top

and it appeared instantly in influxdb and grafana

influxdb server_name=prodInflux,**js=top** host=172.31.231.22 port=8089 measurement=NGINX enabled=true;

influxdb_dynamic_fields client_ip="$remote_addr" lb_node="$host" upstream="$upstream" up_status="$status" resp_t="$upstream_response_time" upstream_addr="$upstream_addr" UUID="$upstream_http_x_uuid" Sec-WebSocket-Key="$http_sec_websocket_key";
